[project]
name = "simple_currency_converter"
version = "0.1.1"
description = "Simple currency converter"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "requests",
    "types-requests",
]

[project.scripts]
simple-currency-converter = "simple_currency_converter.__main__:main"
