# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: astral-sh/setup-uv
      # You may pin to the exact commit or the version.
      # uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231
      uses: astral-sh/setup-uv@v5.3.1
              
